"""
Generates report from alerts generated by rules
"""

# python modules
import os
import sys
import traceback

# local modules
import pe

# directory of rules
import rules

# import rules
for r in rules.__all__:
  __import__('rules.' + r)

# obj = pe.PE('tests/55_m')
# print obj

try:
  alerts = []
  # parse the file specified at the comand line
  obj = pe.PE(sys.argv[1])
  print(obj)
  for r in rules.__all__:
    alerts.extend(sys.modules['rules.' + r].run(obj))
  # display any alerts
  if alerts:
    for a in alerts:
      print(a)
      # display delimiter
      print('-' * 80)
except Exception as e:
  traceback.print_exc()

# # open all files in tests/
# for f in os.listdir('tests'):
#   # display file header
#   print '#' * 80
#   print 'File: ' + f
#   print '#' * 80
#   try:
#     # parse the file specified at the comand line
#     obj = pe.PE('tests/' + f)
#   except Exception as e:
#     print 'ERROR'
#     traceback.print_exc()
#     continue
#   # list holding alerts accross all rules
#   alerts = []

#   for r in rules.__all__:
#     alerts.extend(sys.modules['rules.' + r].run(obj))
#   # import pprint
#   # print pprint.pprint(obj.parse_strings(0, -1, min_length=10), indent=2)

#   # alerts.extend(sys.modules['rules.check_section_strings'].run(obj))

#   # display any alerts
#   if alerts:
#     for a in alerts:
#       print(a)
#       # display delimiter
#       print('-' * 80)
