"""
Generates report from alerts generated by rules
"""

# python modules
import os
import sys
import traceback

# local modules
import pe

# directory of rules
import rules

# import rules
for r in rules.__all__:
  __import__('rules.' + r)

# alerts = []
# obj = pe.PE('tests/42_m')
# alerts.extend(sys.modules['rules.check_section_strings'].run(obj))
# if alerts:
#   for a in alerts:
#     print(a)
#     # display delimiter
#     print('-' * 80)

# open all files in tests/
for f in os.listdir('tests'):
  # display file header
  print '#' * 80
  print 'File: ' + f
  print '#' * 80
  try:
    # parse the file specified at the comand line
    obj = pe.PE('tests/' + f)
  except Exception as e:
    traceback.print_exc()
    continue
  # list holding alerts accross all rules
  alerts = []

  # for r in rules.__all__:
  #   alerts.extend(sys.modules['rules.' + r].run(obj))

  alerts.extend(sys.modules['rules.check_imported_dlls'].run(obj))

  # display any alerts
  if alerts:
    for a in alerts:
      print(a)
      # display delimiter
      print('-' * 80)
