"""
Generates report from alerts generated by rules
"""

# python modules
import os
import sys
import traceback

# local modules
import pe

# directory of rules
import rules

# import rules
for r in rules.__all__:
  __import__('rules.' + r)

# open all files in tests/
for f in os.listdir('tests'):
  # display file header
  print '#' * 80
  print 'File: ' + f
  print '#' * 80
  try:
    # parse the file specified at the comand line
    obj = pe.PE('tests/' + f)
  except Exception as e:
    traceback.print_exc()
    continue
  # list holding alerts accross all rules
  alerts = []

  # run rules
  for r in rules.__all__:
    alerts.extend(sys.modules['rules.' + r].run(obj))

  # run one rule
  # alerts.extend(sys.modules['rules.check_entropy'].run(obj))

  # display any alerts
  if alerts:
    for a in alerts:
      print(a)
      # display delimiter
      print('-' * 80)
